version: '3'

services:
   db:
     image: postgres:latest
     restart: unless-stopped
     env_file:
       - env_file
     volumes:
       - ./db/data:/var/lib/postgresql/data
   web:
     build: web
     depends_on:
       - db
     container_name: web
     command: bash -c "python -c 'from app import db; db.create_all()' && /usr/local/bin/gunicorn -w 2 -b :80 app:app"
     restart: unless-stopped
     volumes:
       - ./web:/usr/src/web
     env_file:
       - env_file
     environment:
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
   default:
     external:
       name: ${NETWORK}
